CREATE WAREHOUSE SALESPULSE360_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE SALESPULSE360_WH;

CREATE DATABASE SALESPULSE360_DB;
USE DATABASE SALESPULSE360_DB;

CREATE SCHEMA RAW_SCHEMA;

CREATE SCHEMA STAGING_SCHEMA;

CREATE SCHEMA ANALYTICS_SCHEMA;