USE SCHEMA RAW_SCHEMA;

CREATE OR REPLACE STAGE SALES_RAW_STAGE
URL = 's3://salespulse360-data/raw/'
CREDENTIALS = (
    AWS_KEY_ID = '<hidden>'
    AWS_SECRET_KEY = '<hidden>'
);

LIST @SALES_RAW_STAGE;


CREATE OR REPLACE FILE FORMAT SALES_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


CREATE OR REPLACE TABLE RAW_SALES_ORDERS (
    ORDER_NUMBER STRING,
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    CUSTOMER_NAME_INDEX NUMBER,
    CHANNEL STRING,
    CURRENCY_CODE STRING,
    WAREHOUSE_CODE STRING,
    DELIVERY_REGION_INDEX NUMBER,
    PRODUCT_DESCRIPTION_INDEX NUMBER,
    ORDER_QUANTITY NUMBER,
    UNIT_PRICE FLOAT,
    TOTAL_UNIT_COST FLOAT,
    TOTAL_REVENUE FLOAT,
    REPLAY_TIMESTAMP TIMESTAMP
);

COPY INTO RAW_SALES_ORDERS
FROM @SALES_RAW_STAGE
FILE_FORMAT = SALES_CSV_FORMAT;

SELECT *
FROM RAW_SALES_ORDERS
LIMIT 10;

SELECT COUNT(*)
FROM RAW_SALES_ORDERS;