USE SCHEMA STAGING_SCHEMA;

CREATE OR REPLACE TABLE STG_SALES_ORDERS AS
SELECT
    ORDER_NUMBER,
    ORDER_DATE,
    SHIP_DATE,
    CUSTOMER_NAME_INDEX,
    CHANNEL,
    CURRENCY_CODE,
    WAREHOUSE_CODE,
    DELIVERY_REGION_INDEX,
    PRODUCT_DESCRIPTION_INDEX,
    ORDER_QUANTITY,
    UNIT_PRICE,
    TOTAL_UNIT_COST,
    TOTAL_REVENUE,
    REPLAY_TIMESTAMP,
    
    -- Calculate delivery duration
    DATEDIFF(
        DAY,
        ORDER_DATE,
        SHIP_DATE
    ) AS DELIVERY_DAYS,

    -- Calculate profit
    (
        TOTAL_REVENUE - TOTAL_UNIT_COST
    ) AS PROFIT,

    -- Calculate profit margin percentage
    ROUND(
        (
            (TOTAL_REVENUE - TOTAL_UNIT_COST)
            / NULLIF(TOTAL_REVENUE, 0)
        ) * 100,
        2
    ) AS PROFIT_MARGIN_PERCENT
FROM SALESPULSE360_DB.RAW_SCHEMA.RAW_SALES_ORDERS;

SELECT *
FROM STG_SALES_ORDERS
LIMIT 10;


SELECT
    DELIVERY_DAYS,
    PROFIT,
    PROFIT_MARGIN_PERCENT
FROM STG_SALES_ORDERS
LIMIT 10;