USE SCHEMA RAW_SCHEMA;

CREATE OR REPLACE STAGE SALES_DIM_STAGE
URL = 's3://salespulse360-data/dimensions/'
CREDENTIALS = (
    AWS_KEY_ID = '<hidden>'
    AWS_SECRET_KEY = '<hidden>'
);

LIST @SALES_DIM_STAGE

CREATE OR REPLACE TABLE RAW_CUSTOMERS (
    CUSTOMER_INDEX NUMBER,
    CUSTOMER_NAME STRING
);

CREATE OR REPLACE TABLE RAW_PRODUCTS (
    PRODUCT_INDEX NUMBER,
    PRODUCT_NAME STRING
);

CREATE OR REPLACE TABLE RAW_REGIONS (
    REGION_INDEX NUMBER,
    SUBURB STRING,
    CITY STRING,
    POSTCODE NUMBER,
    LONGITUDE FLOAT,
    LATITUDE FLOAT,
    FULL_ADDRESS STRING
);

CREATE OR REPLACE FILE FORMAT SALES_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

COPY INTO RAW_REGIONS
FROM @SALES_DIM_STAGE/regions.csv
FILE_FORMAT = SALES_CSV_FORMAT;

SELECT *
FROM RAW_REGIONS
LIMIT 10;

COPY INTO RAW_PRODUCTS
FROM @SALES_DIM_STAGE/products.csv
FILE_FORMAT = SALES_CSV_FORMAT;

SELECT *
FROM RAW_PRODUCTS
LIMIT 10;

COPY INTO RAW_CUSTOMERS
FROM @SALES_DIM_STAGE/customers.csv
FILE_FORMAT = SALES_CSV_FORMAT;

SELECT *
FROM RAW_CUSTOMERS
LIMIT 10;