USE SCHEMA ANALYTICS_SCHEMA;

CREATE OR REPLACE TABLE SALES_ANALYTICS_MASTER AS
SELECT
    F.ORDER_NUMBER,
    F.ORDER_DATE,
    F.SHIP_DATE,
    F.CHANNEL,
    F.CURRENCY_CODE,
    F.WAREHOUSE_CODE,
    F.ORDER_QUANTITY,
    F.UNIT_PRICE,
    F.TOTAL_UNIT_COST,
    F.TOTAL_REVENUE,
    F.PROFIT,
    F.PROFIT_MARGIN_PERCENT,
    F.DELIVERY_DAYS,

    -- Customer Information
    C.CUSTOMER_NAME,

    -- Product Information
    P.PRODUCT_NAME,

    -- Region Information
    R.SUBURB,
    R.CITY,
    R.POSTCODE,
    R.FULL_ADDRESS,
    R.LONGITUDE,
    R.LATITUDE

FROM SALESPULSE360_DB.STAGING_SCHEMA.STG_SALES_ORDERS F

LEFT JOIN SALESPULSE360_DB.RAW_SCHEMA.RAW_CUSTOMERS C
ON F.CUSTOMER_NAME_INDEX = C.CUSTOMER_INDEX

LEFT JOIN SALESPULSE360_DB.RAW_SCHEMA.RAW_PRODUCTS P
ON F.PRODUCT_DESCRIPTION_INDEX = P.PRODUCT_INDEX

LEFT JOIN SALESPULSE360_DB.RAW_SCHEMA.RAW_REGIONS R
ON F.DELIVERY_REGION_INDEX = R.REGION_INDEX;

SELECT *
FROM SALES_ANALYTICS_MASTER
LIMIT 10;