USE SCHEMA ANALYTICS_SCHEMA;


CREATE OR REPLACE TABLE SALES_TREND_ANALYTICS AS
SELECT
    ORDER_DATE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(TOTAL_REVENUE) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN
FROM SALESPULSE360_DB.STAGING_SCHEMA.STG_SALES_ORDERS
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

SELECT *
FROM SALES_TREND_ANALYTICS
LIMIT 10;


CREATE OR REPLACE TABLE MONTHLY_SALES_TRENDS AS
SELECT
    YEAR(ORDER_DATE) AS SALES_YEAR,
    MONTH(ORDER_DATE) AS SALES_MONTH,
    SUM(TOTAL_REVENUE) AS MONTHLY_REVENUE,
    SUM(PROFIT) AS MONTHLY_PROFIT,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS
FROM SALESPULSE360_DB.STAGING_SCHEMA.STG_SALES_ORDERS
GROUP BY
    YEAR(ORDER_DATE),
    MONTH(ORDER_DATE)
ORDER BY
    SALES_YEAR,
    SALES_MONTH;

SELECT *
FROM MONTHLY_SALES_TRENDS
LIMIT 10;


CREATE OR REPLACE TABLE WAREHOUSE_PERFORMANCE_ANALYTICS AS
SELECT
    WAREHOUSE_CODE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS,
    MAX(DELIVERY_DAYS) AS MAX_DELIVERY_DAYS,
    MIN(DELIVERY_DAYS) AS MIN_DELIVERY_DAYS,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN
FROM SALES_ANALYTICS_MASTER
GROUP BY WAREHOUSE_CODE
ORDER BY TOTAL_REVENUE DESC;

SELECT *
FROM WAREHOUSE_PERFORMANCE_ANALYTICS
LIMIT 10;


CREATE OR REPLACE TABLE PRODUCT_PERFORMANCE_ANALYTICS AS
SELECT
    PRODUCT_NAME,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(UNIT_PRICE) AS AVG_UNIT_PRICE
FROM SALES_ANALYTICS_MASTER
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT*
FROM PRODUCT_PERFORMANCE_ANALYTICS
LIMIT 10;


CREATE OR REPLACE TABLE REGIONAL_SALES_ANALYTICS AS
SELECT
    CITY,
    SUBURB,
    POSTCODE,
    LATITUDE,
    LONGITUDE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS
FROM SALES_ANALYTICS_MASTER
GROUP BY
    CITY,
    SUBURB,
    POSTCODE,
    LATITUDE,
    LONGITUDE
ORDER BY TOTAL_REVENUE DESC;

SELECT*
FROM REGIONAL_SALES_ANALYTICS
LIMIT 10;


CREATE OR REPLACE TABLE CUSTOMER_BEHAVIOR_ANALYTICS AS
SELECT
    CUSTOMER_NAME,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY_PURCHASED,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS,
    MAX(TOTAL_REVENUE) AS HIGHEST_SINGLE_ORDER_VALUE
FROM SALES_ANALYTICS_MASTER
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT*
FROM CUSTOMER_BEHAVIOR_ANALYTICS
LIMIT 10;


CREATE OR REPLACE TABLE CHANNEL_PERFORMANCE_ANALYTICS AS
SELECT
    CHANNEL,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS
FROM SALES_ANALYTICS_MASTER
GROUP BY CHANNEL
ORDER BY TOTAL_REVENUE DESC;

SELECT*
FROM CHANNEL_PERFORMANCE_ANALYTICS
LIMIT 10;


CREATE OR REPLACE TABLE CURRENCY_ANALYTICS AS
SELECT
    CURRENCY_CODE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN
FROM SALES_ANALYTICS_MASTER
GROUP BY CURRENCY_CODE
ORDER BY TOTAL_REVENUE DESC;

SELECT*
FROM CURRENCY_ANALYTICS
LIMIT 10;


CREATE OR REPLACE TABLE PROFITABILITY_ANALYTICS AS
SELECT
    PRODUCT_NAME,
    CHANNEL,
    CURRENCY_CODE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY,
    AVG(UNIT_PRICE) AS AVG_UNIT_PRICE,
    SUM(TOTAL_UNIT_COST) AS TOTAL_COST,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN
FROM SALES_ANALYTICS_MASTER
GROUP BY
    PRODUCT_NAME,
    CHANNEL,
    CURRENCY_CODE
ORDER BY TOTAL_PROFIT DESC;

SELECT*
FROM PROFITABILITY_ANALYTICS
LIMIT 10;


CREATE OR REPLACE TABLE EXECUTIVE_KPI_SUMMARY AS
SELECT
    COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(TOTAL_REVENUE) AS TOTAL_SALES,
    SUM(TOTAL_UNIT_COST) AS TOTAL_COST,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(UNIT_PRICE) AS AVG_UNIT_PRICE,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS,
    COUNT(DISTINCT CUSTOMER_NAME) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_NAME) AS TOTAL_PRODUCTS,
    COUNT(DISTINCT CITY) AS TOTAL_CITIES
FROM SALES_ANALYTICS_MASTER;

SELECT*
FROM EXECUTIVE_KPI_SUMMARY
LIMIT 10;