USE DATABASE SALESPULSE360_DB;
USE SCHEMA ANALYTICS_SCHEMA;

CREATE OR REPLACE PROCEDURE REFRESH_ANALYTICS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

CREATE OR REPLACE TABLE SALES_ANALYTICS_MASTER AS
SELECT
    F.ORDER_NUMBER,
    F.ORDER_DATE,
    F.SHIP_DATE,
    F.CHANNEL,
    F.CURRENCY_CODE,
    F.WAREHOUSE_CODE,
    F.ORDER_QUANTITY,
    F.UNIT_PRICE,
    F.TOTAL_UNIT_COST,
    F.TOTAL_REVENUE,
    F.PROFIT,
    F.PROFIT_MARGIN_PERCENT,
    F.DELIVERY_DAYS,

    -- Customer Information
    C.CUSTOMER_NAME,

    -- Product Information
    P.PRODUCT_NAME,

    -- Region Information
    R.SUBURB,
    R.CITY,
    R.POSTCODE,
    R.FULL_ADDRESS,
    R.LONGITUDE,
    R.LATITUDE

FROM SALESPULSE360_DB.STAGING_SCHEMA.STG_SALES_ORDERS F

LEFT JOIN SALESPULSE360_DB.RAW_SCHEMA.RAW_CUSTOMERS C
ON F.CUSTOMER_NAME_INDEX = C.CUSTOMER_INDEX

LEFT JOIN SALESPULSE360_DB.RAW_SCHEMA.RAW_PRODUCTS P
ON F.PRODUCT_DESCRIPTION_INDEX = P.PRODUCT_INDEX

LEFT JOIN SALESPULSE360_DB.RAW_SCHEMA.RAW_REGIONS R
ON F.DELIVERY_REGION_INDEX = R.REGION_INDEX;

CREATE OR REPLACE TABLE SALES_TREND_ANALYTICS AS
SELECT
    ORDER_DATE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(TOTAL_REVENUE) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN
FROM SALESPULSE360_DB.STAGING_SCHEMA.STG_SALES_ORDERS
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;


CREATE OR REPLACE TABLE MONTHLY_SALES_TRENDS AS
SELECT
    YEAR(ORDER_DATE) AS SALES_YEAR,
    MONTH(ORDER_DATE) AS SALES_MONTH,
    SUM(TOTAL_REVENUE) AS MONTHLY_REVENUE,
    SUM(PROFIT) AS MONTHLY_PROFIT,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS
FROM SALESPULSE360_DB.STAGING_SCHEMA.STG_SALES_ORDERS
GROUP BY
    YEAR(ORDER_DATE),
    MONTH(ORDER_DATE)
ORDER BY
    SALES_YEAR,
    SALES_MONTH;


CREATE OR REPLACE TABLE WAREHOUSE_PERFORMANCE_ANALYTICS AS
SELECT
    WAREHOUSE_CODE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS,
    MAX(DELIVERY_DAYS) AS MAX_DELIVERY_DAYS,
    MIN(DELIVERY_DAYS) AS MIN_DELIVERY_DAYS,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN
FROM SALES_ANALYTICS_MASTER
GROUP BY WAREHOUSE_CODE
ORDER BY TOTAL_REVENUE DESC;



CREATE OR REPLACE TABLE PRODUCT_PERFORMANCE_ANALYTICS AS
SELECT
    PRODUCT_NAME,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(UNIT_PRICE) AS AVG_UNIT_PRICE
FROM SALES_ANALYTICS_MASTER
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;



CREATE OR REPLACE TABLE REGIONAL_SALES_ANALYTICS AS
SELECT
    CITY,
    SUBURB,
    POSTCODE,
    LATITUDE,
    LONGITUDE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS
FROM SALES_ANALYTICS_MASTER
GROUP BY
    CITY,
    SUBURB,
    POSTCODE,
    LATITUDE,
    LONGITUDE
ORDER BY TOTAL_REVENUE DESC;



CREATE OR REPLACE TABLE CUSTOMER_BEHAVIOR_ANALYTICS AS
SELECT
    CUSTOMER_NAME,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY_PURCHASED,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS,
    MAX(TOTAL_REVENUE) AS HIGHEST_SINGLE_ORDER_VALUE
FROM SALES_ANALYTICS_MASTER
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;



CREATE OR REPLACE TABLE CHANNEL_PERFORMANCE_ANALYTICS AS
SELECT
    CHANNEL,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS
FROM SALES_ANALYTICS_MASTER
GROUP BY CHANNEL
ORDER BY TOTAL_REVENUE DESC;



CREATE OR REPLACE TABLE CURRENCY_ANALYTICS AS
SELECT
    CURRENCY_CODE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN
FROM SALES_ANALYTICS_MASTER
GROUP BY CURRENCY_CODE
ORDER BY TOTAL_REVENUE DESC;



CREATE OR REPLACE TABLE PROFITABILITY_ANALYTICS AS
SELECT
    PRODUCT_NAME,
    CHANNEL,
    CURRENCY_CODE,
    COUNT(ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY,
    AVG(UNIT_PRICE) AS AVG_UNIT_PRICE,
    SUM(ORDER_QUANTITY * TOTAL_UNIT_COST) AS TOTAL_COST,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN
FROM SALES_ANALYTICS_MASTER
GROUP BY
    PRODUCT_NAME,
    CHANNEL,
    CURRENCY_CODE
ORDER BY TOTAL_PROFIT DESC;



CREATE OR REPLACE TABLE EXECUTIVE_KPI_SUMMARY AS
SELECT
    COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS,
    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(TOTAL_REVENUE) AS TOTAL_SALES,
    SUM(ORDER_QUANTITY * TOTAL_UNIT_COST) AS TOTAL_COST,
    SUM(PROFIT) AS TOTAL_PROFIT,
    AVG(UNIT_PRICE) AS AVG_UNIT_PRICE,
    AVG(PROFIT_MARGIN_PERCENT) AS AVG_PROFIT_MARGIN,
    AVG(DELIVERY_DAYS) AS AVG_DELIVERY_DAYS,
    COUNT(DISTINCT CUSTOMER_NAME) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_NAME) AS TOTAL_PRODUCTS,
    COUNT(DISTINCT CITY) AS TOTAL_CITIES
FROM SALES_ANALYTICS_MASTER;

RETURN 'Analytics Refreshed Successfully';

END;
$$;

CALL REFRESH_ANALYTICS();

